"""Build-generated resource module, compiled by each packaged interpreter."""
import base64
import hashlib
from pathlib import Path
import sys
import zlib


def bundle(repo: Path, destinations: list[Path]) -> None:
    sources = {name: repo / 'tc_template' / name for name in
               ('TcCom.ps1', 'TcHmiBinding.ps1', 'TcHmiServer.ps1', 'TcHmiItems.ps1', 'TcHmiProject.ps1')}
    sources['TcIoConfiguration.ps1'] = repo / 'scripts' / 'Invoke-TcIoConfiguration.ps1'
    resources = {}
    for name, source in sources.items():
        data = source.read_bytes()
        resources[name] = (hashlib.sha256(data).hexdigest(), base64.b85encode(zlib.compress(data, 9)).decode('ascii'))
    for dest in destinations:
        (dest / '_script_bundle.py').write_text(
            '# Generated by bundle_tool_scripts.py; do not edit.\nSCRIPTS = ' + repr(resources) + '\n',
            encoding='ascii')


if __name__ == '__main__':
    bundle(Path(sys.argv[1]), [Path(value) for value in sys.argv[2:]])
